services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass secret
    volumes:
      - redis:/data
volumes:
  postgres: {}
  redis: {}
